server:
  port: 8080

spring:
  application:
    name: study-java
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.cheng: DEBUG
    org.springframework.web: DEBUG 